services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: syncdoc
      POSTGRES_PASSWORD: syncdoc_prod_2026!
      POSTGRES_DB: syncdoc
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  app:
    image: ghcr.io/canoelitose/syncdoc:latest
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://syncdoc:syncdoc_prod_2026!@db:5432/syncdoc
      NEXTAUTH_SECRET: jRMjtEOlgc9LE5mdPbXOLk/JhxbeSTBhSIF5VdpBfyc=
      NEXTAUTH_URL: http://10.10.11.55:3000
    depends_on:
      - db
    restart: unless-stopped

volumes:
  pgdata:
